<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE hdr:Message [
        <!ELEMENT hdr:Message (hdr:AppHdr|hdr:FIToFICstmrCdtTrf)*>
        <!ATTLIST hdr:Message
                xmlns CDATA #REQUIRED>
        <!ELEMENT hdr:AppHdr (Fr|To|BizMsgIdr|MsgDefIdr|BizSvc|CreDt|Sgntr)*>
        <!ATTLIST hdr:AppHdr
                xmlns CDATA #REQUIRED>
        <!ELEMENT Fr (FIId)*>
        <!ELEMENT FIId (FinInstnId)*>
        <!ELEMENT FinInstnId (ClrSysMmbId|BICFI)*>
        <!ELEMENT ClrSysMmbId (ClrSysId|MmbId)*>
        <!ELEMENT ClrSysId (Prtry)*>
        <!ELEMENT Prtry (#PCDATA)>
        <!ELEMENT MmbId (#PCDATA)>
        <!ELEMENT To (FIId)*>
        <!ELEMENT BizMsgIdr (#PCDATA)>
        <!ELEMENT MsgDefIdr (#PCDATA)>
        <!ELEMENT BizSvc (#PCDATA)>
        <!ELEMENT CreDt (#PCDATA)>
        <!ELEMENT Sgntr (Signature)*>
        <!ELEMENT Signature (SignedInfo|SignatureValue|KeyInfo)*>
        <!ATTLIST Signature
                xmlns CDATA #REQUIRED>
        <!ELEMENT SignedInfo (CanonicalizationMethod|SignatureMethod|Reference)*>
        <!ELEMENT CanonicalizationMethod (#PCDATA)>
        <!ATTLIST CanonicalizationMethod
                Algorithm CDATA #REQUIRED>
        <!ELEMENT SignatureMethod (#PCDATA)>
        <!ATTLIST SignatureMethod
                Algorithm CDATA #REQUIRED>
        <!ELEMENT Reference (Transforms|DigestMethod|DigestValue)*>
        <!ATTLIST Reference
                URI CDATA #REQUIRED>
        <!ELEMENT Transforms (Transform)*>
        <!ELEMENT Transform (#PCDATA)>
        <!ATTLIST Transform
                Algorithm CDATA #REQUIRED>
        <!ELEMENT DigestMethod (#PCDATA)>
        <!ATTLIST DigestMethod
                Algorithm CDATA #REQUIRED>
        <!ELEMENT DigestValue (#PCDATA)>
        <!ELEMENT SignatureValue (#PCDATA)>
        <!ELEMENT KeyInfo (X509Data)*>
        <!ELEMENT X509Data (X509SubjectName|X509IssuerSerial)*>
        <!ELEMENT X509SubjectName (#PCDATA)>
        <!ELEMENT X509IssuerSerial (X509IssuerName|X509SerialNumber)*>
        <!ELEMENT X509IssuerName (#PCDATA)>
        <!ELEMENT X509SerialNumber (#PCDATA)>
        <!ELEMENT hdr:FIToFICstmrCdtTrf (GrpHdr|CdtTrfTxInf|SplmtryData)*>
        <!ATTLIST hdr:FIToFICstmrCdtTrf
                xmlns CDATA #REQUIRED>
        <!ELEMENT GrpHdr (MsgId|CreDtTm|NbOfTxs|TtlIntrBkSttlmAmt|IntrBkSttlmDt|SttlmInf|PmtTpInf|InstgAgt)*>
        <!ELEMENT MsgId (#PCDATA)>
        <!ELEMENT CreDtTm (#PCDATA)>
        <!ELEMENT NbOfTxs (#PCDATA)>
        <!ELEMENT TtlIntrBkSttlmAmt (#PCDATA)>
        <!ATTLIST TtlIntrBkSttlmAmt
                Ccy CDATA #REQUIRED>
        <!ELEMENT IntrBkSttlmDt (#PCDATA)>
        <!ELEMENT SttlmInf (SttlmMtd|ClrSys)*>
        <!ELEMENT SttlmMtd (#PCDATA)>
        <!ELEMENT ClrSys (Prtry)*>
        <!ELEMENT PmtTpInf (SvcLvl|LclInstrm|CtgyPurp)*>
        <!ELEMENT SvcLvl (Prtry)*>
        <!ELEMENT LclInstrm (Cd)*>
        <!ELEMENT Cd (#PCDATA)>
        <!ELEMENT CtgyPurp (Cd)*>
        <!ELEMENT InstgAgt (FinInstnId)*>
        <!ELEMENT BICFI (#PCDATA)>
        <!ELEMENT CdtTrfTxInf (PmtId|IntrBkSttlmAmt|AccptncDtTm|InstdAmt|XchgRate|ChrgBr|UltmtDbtr|Dbtr|DbtrAcct|DbtrAgt|CdtrAgt|Cdtr|CdtrAcct|UltmtCdtr|InstrForCdtrAgt|RmtInf)*>
        <!ELEMENT PmtId (InstrId|EndToEndId|TxId)*>
        <!ELEMENT InstrId (#PCDATA)>
        <!ELEMENT EndToEndId (#PCDATA)>
        <!ELEMENT TxId (#PCDATA)>
        <!ELEMENT IntrBkSttlmAmt (#PCDATA)>
        <!ATTLIST IntrBkSttlmAmt
                Ccy CDATA #REQUIRED>
        <!ELEMENT AccptncDtTm (#PCDATA)>
        <!ELEMENT InstdAmt (#PCDATA)>
        <!ATTLIST InstdAmt
                Ccy CDATA #REQUIRED>
        <!ELEMENT XchgRate (#PCDATA)>
        <!ELEMENT ChrgBr (#PCDATA)>
        <!ELEMENT UltmtDbtr (Nm)*>
        <!ELEMENT Nm (#PCDATA)>
        <!ELEMENT Dbtr (Nm|PstlAdr)*>
        <!ELEMENT PstlAdr (Ctry|AdrLine)*>
        <!ELEMENT Ctry (#PCDATA)>
        <!ELEMENT AdrLine (#PCDATA)>
        <!ELEMENT DbtrAcct (Id)*>
        <!ELEMENT Id (Othr)*>
        <!ELEMENT Othr (Id|SchmeNm)*>
        <!ELEMENT SchmeNm (Cd)*>
        <!ELEMENT DbtrAgt (FinInstnId)*>
        <!ELEMENT CdtrAgt (FinInstnId)*>
        <!ELEMENT Cdtr (Nm|PstlAdr)*>
        <!ELEMENT CdtrAcct (Id)*>
        <!ELEMENT UltmtCdtr (Nm|CtryOfRes|CtctDtls)*>
        <!ELEMENT CtryOfRes (#PCDATA)>
        <!ELEMENT CtctDtls (EmailAdr|Othr)*>
        <!ELEMENT EmailAdr (#PCDATA)>
        <!ELEMENT InstrForCdtrAgt (Cd|InstrInf)*>
        <!ELEMENT InstrInf (#PCDATA)>
        <!ELEMENT RmtInf (Ustrd)*>
        <!ELEMENT Ustrd (#PCDATA)>
        <!ELEMENT SplmtryData (Envlp)*>
        <!ELEMENT Envlp (AuditInfo)*>
        <!ELEMENT AuditInfo (IP|PC)*>
        <!ELEMENT IP (#PCDATA)>
        <!ELEMENT PC (#PCDATA)>
        ]>
<hdr:Message xmlns="urn:montran:message.01">
    <hdr:AppHdr xmlns="urn:iso:std:iso:20022:tech:xsd:head.001.001.01">
        <Fr>
            <FIId>
                <FinInstnId>
                    <ClrSysMmbId>
                        <ClrSysId>
                            <Prtry>PAPSS</Prtry>
                        </ClrSysId>
                        <MmbId>KE1002</MmbId>
                    </ClrSysMmbId>
                </FinInstnId>
            </FIId>
        </Fr>
        <To>
            <FIId>
                <FinInstnId>
                    <ClrSysMmbId>
                        <ClrSysId>
                            <Prtry>PAPSS</Prtry>
                        </ClrSysId>
                        <MmbId>XA0001</MmbId>
                    </ClrSysMmbId>
                </FinInstnId>
            </FIId>
        </To>
        <BizMsgIdr>20240123KE1002120503</BizMsgIdr>
        <MsgDefIdr>pacs.008.001.07</MsgDefIdr>
        <BizSvc>RTP</BizSvc>
        <CreDt>2024-01-23T10:05:03.635Z</CreDt>
        <Sgntr>
            <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
                <SignedInfo>
                    <CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315"/>
                    <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"/>
                    <Reference URI="">
                        <Transforms>
                            <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                            <Transform Algorithm="http://www.w3.org/2006/12/xml-c14n11"/>
                        </Transforms>
                        <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"/>
                        <DigestValue>fVqxWejFalRusbvs9inaoyMXAfmwJzpyFa5Ebt92aA0=</DigestValue>
                    </Reference>
                </SignedInfo>
                <SignatureValue>vJ5JCxAVU7RGPPazGNSut56p/QOnDVAEyU1jZYJzY8+vrE10wKO8AhA7v+5gSiRH1tRfhKvP4J/e&#13;
                    Cwt/z1suXA2i1pWu9/GK2GSs5AQtqEfWFxeAzS7G5GIwBgrWaZzc4I8GIHZlH2l2Avsrj+A5DV3i&#13;
                    q9f1fLuf77TlItSCB4DLz69FUPOtEEHe62HVOHkgOYpnmjP91XnmPbKzdkqLK2rm5DnmXrKcAWH8&#13;
                    2CPTjMd9w7G5yUgk4mHmjOn/nHVtCNTw4S0XRYmTxGR4SV3rn5cxu6587NotKGtAPIZuwO5HD1TH&#13;
                    hSPJxWeB4e6t4UaQXaDTzpLOxIZ1unYS9/kbZw==</SignatureValue>
                <KeyInfo>
                    <X509Data>
                        <X509SubjectName>CN=tezk-c1</X509SubjectName>
                        <X509IssuerSerial>
                            <X509IssuerName>CN=AFXM CA</X509IssuerName>
                            <X509SerialNumber>222063791874351954580927885950191632387</X509SerialNumber>
                        </X509IssuerSerial>
                    </X509Data>
                </KeyInfo>
            </Signature>
        </Sgntr>
    </hdr:AppHdr>
    <hdr:FIToFICstmrCdtTrf xmlns="urn:iso:std:iso:20022:tech:xsd:pacs.008.001.07">
        <GrpHdr>
            <MsgId>20240123KE1002120503</MsgId>
            <CreDtTm>2024-01-23T10:05:03.635Z</CreDtTm>
            <NbOfTxs>1</NbOfTxs>
            <TtlIntrBkSttlmAmt Ccy="GNF">100000</TtlIntrBkSttlmAmt>
            <IntrBkSttlmDt>2024-01-23</IntrBkSttlmDt>
            <SttlmInf>
                <SttlmMtd>CLRG</SttlmMtd>
                <ClrSys>
                    <Prtry>PAPSS</Prtry>
                </ClrSys>
            </SttlmInf>
            <PmtTpInf>
                <SvcLvl>
                    <Prtry>INST</Prtry>
                </SvcLvl>
                <LclInstrm>
                    <Cd>ET</Cd>
                </LclInstrm>
                <CtgyPurp>
                    <Cd>SUPP</Cd>
                </CtgyPurp>
            </PmtTpInf>
            <InstgAgt>
                <FinInstnId>
                    <BICFI>UBAGGNCN</BICFI>
                    <ClrSysMmbId>
                        <ClrSysId>
                            <Prtry>PAPSS</Prtry>
                        </ClrSysId>
                        <MmbId>KE1002</MmbId>
                    </ClrSysMmbId>
                </FinInstnId>
            </InstgAgt>
        </GrpHdr>
        <CdtTrfTxInf>
            <PmtId>
                <InstrId>20240123KE1002120503</InstrId>
                <EndToEndId>ENDTOENDREF123</EndToEndId>
                <TxId>20240123KE1002120503</TxId>
            </PmtId>
            <IntrBkSttlmAmt Ccy="GNF">100000</IntrBkSttlmAmt>
            <AccptncDtTm>2024-01-23T10:05:03.635Z</AccptncDtTm>
            <InstdAmt Ccy="NGN"/>
            <XchgRate>1</XchgRate>
            <ChrgBr>SLEV</ChrgBr>
            <UltmtDbtr>
                <Nm>John Doe</Nm>
            </UltmtDbtr>
            <Dbtr>
                <Nm>John Doe</Nm>
                <PstlAdr>
                    <Ctry>GN</Ctry>
                    <AdrLine>user@papss.com</AdrLine>
                </PstlAdr>
            </Dbtr>
            <DbtrAcct>
                <Id>
                    <Othr>
                        <Id>1000000000</Id>
                        <SchmeNm>
                            <Cd>BBAN</Cd>
                        </SchmeNm>
                    </Othr>
                </Id>
            </DbtrAcct>
            <DbtrAgt>
                <FinInstnId>
                    <BICFI>UBAGGNCN</BICFI>
                    <ClrSysMmbId>
                        <MmbId>KE1002</MmbId>
                    </ClrSysMmbId>
                </FinInstnId>
            </DbtrAgt>
            <CdtrAgt>
                <FinInstnId>
                    <BICFI>AFXMNGNG</BICFI>
                    <ClrSysMmbId>
                        <ClrSysId>
                            <Prtry>PAPSS</Prtry>
                        </ClrSysId>
                        <MmbId>NG2020</MmbId>
                    </ClrSysMmbId>
                </FinInstnId>
            </CdtrAgt>
            <Cdtr>
                <Nm>Mr Ultimate Papss User</Nm>
                <PstlAdr>
                    <Ctry>NG</Ctry>
                    <AdrLine>123 Street Number NG</AdrLine>
                </PstlAdr>
            </Cdtr>
            <CdtrAcct>
                <Id>
                    <Othr>
                        <Id>1000000000</Id>
                        <SchmeNm>
                            <Cd>BBAN</Cd>
                        </SchmeNm>
                    </Othr>
                </Id>
            </CdtrAcct>
            <UltmtCdtr>
                <Nm>Mr Ultimate Papss User</Nm>
                <CtryOfRes>NG</CtryOfRes>
                <CtctDtls>
                    <EmailAdr>
                        user@papss.com
                    </EmailAdr>
                    <Othr>002630721234567</Othr>
                </CtctDtls>
            </UltmtCdtr>
            <InstrForCdtrAgt>
                <Cd>PHOB</Cd>
                <InstrInf>HBSLAU4T/1000000000/LT499228</InstrInf>
            </InstrForCdtrAgt>
            <RmtInf>
                <Ustrd>Trade Transfer Invoice for purchase of Cassava</Ustrd>
            </RmtInf>
        </CdtTrfTxInf>
        <SplmtryData>
            <Envlp>
                <AuditInfo>
                    <IP>10.77.7.13</IP>
                    <PC>vi-papss</PC>
                </AuditInfo>
            </Envlp>
        </SplmtryData>
    </hdr:FIToFICstmrCdtTrf>
</hdr:Message>

